class ViewController:
    SCROLL_NO_MARGINS = 0, 0, 0, 0
    SCROLL_MARGINS = 10, 10, 10, 10
    DEFAULT_SPACING = 10
    NO_SPACING = 0
    MAX_DISPLAY_ROWS = 4
    DEFAULT_DISPLAY_ROWS = 3
    MIN_DISPLAY_ROWS = 2
    DISPLAY_COLUMNS = ...
    DISPLAY_PADDING = 10
