class Schedule:
    ASSET_JOB_START_DELAY = 100
    FOREX_JOB_START_DELAY = 120
    INDEX_JOB_START_DELAY = 140
    CRYPTO_JOB_START_DELAY = 160
    COMMODITY_JOB_START_DELAY = 180
    BATCH_ASSETS_JOBS_DELAY = 60
    BATCH_MARKET_JOBS_DELAY = 80
    DEFAULT_DELAY = 100
    DEFAULT_MULTIPLIER = 2